### ISSUE TITLE
:bulb: Adicionar o `tabnews-sdk` à lista de `TabProjetos`

### ISSUE THREAD

**Issue by kaique-soares** [leoferreiralima/tabnews-sdk#41]
Fala @leoferreiralima, eu vi sua [publicação no TabNews](https://www.tabnews.com.br/leoferreiralima/tabnews-sdk-publiquei-minha-primeira-biblioteca-no-npm) e achei muito massa o projeto meu caro :handshake: 

Por falar em projeto, um bem bacana é o [TabProjetos](https://github.com/gabrielsozinho/TabProjetos) do @gabrielsozinho, onde são listados projetos que foram construídos à partir do TabNews.

Você permite que **tabnews-sdk** seja listado no **TabProjetos**? Caso sim, posso submeter uma PR para o repositório do **TabProjetos**, o que acha?

**Comment by kaique-soares** [comment]
@leoferreiralima :sweat_smile: Acabei de ver sua [PR](https://github.com/gabrielsozinho/TabProjetos/pull/7)

**Comment by leoferreiralima** [comment]
@kaique-soares muito obrigado, realmente já fiz a PR lá, contudo sinta-se livre para contribuir de qualquer maneira aqui!
