### ISSUE TITLE
`tabnews.spec.ts` com um teste duplicado?

### ISSUE THREAD

**Issue by kaique-soares** [leoferreiralima/tabnews-sdk#51]
Fala @leoferreiralima :+1: 

Estou estudando o projeto para me familiarizar e como **felizmente** :tada: existem testes, venho alternando entre eles e as implementações. Durante esse processo encontrei no arquivo `tabnews.spec.ts`, os seguintes testes que me parece estarem duplicados ou posso ter deixado passar algum detalhe :handshake:. Pode me confirmar?

https://github.com/leoferreiralima/tabnews-sdk/blob/1c10eaff0870f445d34b2d0c2ae9d63d2a95b859/src/tabnews.spec.ts#L28-L49

---

Em paralelo, no mesmo arquivo o que acha sobre alterar a descrição do seguinte teste para `should instantiate without config and without env`?

https://github.com/leoferreiralima/tabnews-sdk/blob/1c10eaff0870f445d34b2d0c2ae9d63d2a95b859/src/tabnews.spec.ts#L9-L14

**Comment by leoferreiralima** [comment]
Sobre o ponto do código duplicado realmente está

Sobre o ponto do nome do test o env faz parte do config, mas para mim tudo bem renomear!

**Comment by kaique-soares** [comment]
> Sobre o ponto do nome do test o env faz parte do config, mas para mim tudo bem renomear!

Eu abri a PR #52 e nela eu remomeei a mensagem para _should instantiate without **credentials** and without env_ porque de fato as `envs` fazem do config :sweat_smile:

**Comment by kaique-soares** [comment]
- Resolvido nesta PR que #52
